#!/bin/bash
ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
CURDIR=$(pwd)
cd $ROOT
source build_hw_configs.sh

rm bench/run.conf
source bench/build_configs.sh

make clean -C bench
rm -r bench/out
mkdir -p bench/out/cores
mkdir -p bench/out/logs

VAR_LOG_MIN_LEVEL=LOG_LEVEL_PANIC
VAR_LOG_LEVEL=LOG_LEVEL_ERROR

VAR_LOG_TAG_BASIC=ON
VAR_LOG_TAG_BASIC_NUM=$(( 2#1 ))
VAR_LOG_TAG_VECTOR=ON
VAR_LOG_TAG_VECTOR_NUM=$(( 2#10 ))
VAR_LOG_TAG_CLUSTER=ON
VAR_LOG_TAG_CLUSTER_NUM=$(( 2#100 ))
VAR_LOG_TAG_BUFFER=ON
VAR_LOG_TAG_BUFFER_NUM=$(( 2#1000 ))
VAR_LOG_TAG_DIVFTREE_VERTEX=ON
VAR_LOG_TAG_DIVFTREE_VERTEX_NUM=$(( 2#10000 ))
VAR_LOG_TAG_DIVFTREE=ON
VAR_LOG_TAG_DIVFTREE_NUM=$(( 2#100000 ))
VAR_LOG_TAG_CLUSTERING=ON
VAR_LOG_TAG_CLUSTERING_NUM=$(( 2#1000000 ))
VAR_LOG_TAG_MEMORY=ON
VAR_LOG_TAG_MEMORY_NUM=$(( 2#10000000 ))
VAR_LOG_TAG_LOCK=OFF
VAR_LOG_TAG_LOCK_NUM=$(( 2#100000000 ))
VAR_LOG_TAG_THREAD=ON
VAR_LOG_TAG_THREAD_NUM=$(( 2#1000000000 ))
VAR_LOG_TAG_RDMA=ON
VAR_LOG_TAG_RDMA_NUM=$(( 2#10000000000 ))
VAR_LOG_TAG_HANG_DETECTOR=ON
VAR_LOG_TAG_HANG_DETECTOR_NUM=$(( 2#100000000000 ))
VAR_LOG_TAG_NOT_IMPLEMENTED=ON
VAR_LOG_TAG_NOT_IMPLEMENTED_NUM=$(( 2#1000000000000 ))
VAR_LOG_TAG_TEST=ON
VAR_LOG_TAG_TEST_NUM=$(( 2#10000000000000 ))

VAR_LOG_TAG=0
if [ $VAR_LOG_TAG_BASIC == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_BASIC_NUM ))
fi
if [ $VAR_LOG_TAG_VECTOR == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_VECTOR_NUM ))
fi
if [ $VAR_LOG_TAG_CLUSTER == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_CLUSTER_NUM ))
fi
if [ $VAR_LOG_TAG_BUFFER == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_BUFFER_NUM ))
fi
if [ $VAR_LOG_TAG_DIVFTREE_VERTEX == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_DIVFTREE_VERTEX_NUM ))
fi
if [ $VAR_LOG_TAG_DIVFTREE == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_DIVFTREE_NUM ))
fi
if [ $VAR_LOG_TAG_CLUSTERING == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_CLUSTERING_NUM ))
fi
if [ $VAR_LOG_TAG_MEMORY == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_MEMORY_NUM ))
fi
if [ $VAR_LOG_TAG_LOCK == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_LOCK_NUM ))
fi
if [ $VAR_LOG_TAG_THREAD == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_THREAD_NUM ))
fi
if [ $VAR_LOG_TAG_RDMA == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_RDMA_NUM ))
fi
if [ $VAR_LOG_TAG_HANG_DETECTOR == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_HANG_DETECTOR_NUM ))
fi
if [ $VAR_LOG_TAG_NOT_IMPLEMENTED == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_NOT_IMPLEMENTED_NUM ))
fi
if [ $VAR_LOG_TAG_TEST == ON ]; then
    VAR_LOG_TAG=$(( VAR_LOG_TAG | VAR_LOG_TAG_TEST_NUM ))
fi


VAR_PRINT_FUNCTION_NAME_PRETTY=OFF
VAR_PRINT_CALLSTACK_LEVEL=LOG_LEVEL_ZERO
VAR_MAX_LOG_FILE_SIZE_MB=1024
VAR_MAX_LOG_FILE_NUM=10

FLAGS="-DLOG_MIN_LEVEL=$VAR_LOG_MIN_LEVEL -DLOG_LEVEL=$VAR_LOG_LEVEL -DLOG_TAG=$VAR_LOG_TAG"
if [ $VAR_PRINT_FUNCTION_NAME_PRETTY == ON ]; then
    FLAGS="$FLAGS -DPRINT_FUNCTION_NAME_PRETTY"
fi
FLAGS="$FLAGS -DPRINT_CALLSTACK_LEVEL=$VAR_PRINT_CALLSTACK_LEVEL -DMAX_LOG_FILE_SIZE_MB=$VAR_MAX_LOG_FILE_SIZE_MB"
FLAGS="$FLAGS -DMAX_LOG_FILE_NUM=$VAR_MAX_LOG_FILE_NUM"
FLAGS="$FLAGS $*"
# make -C bench DEFINES="-DTESTING $*"
make -C bench DEFINES="$FLAGS"
cd $CURDIR